name: earth-analytics-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn

  # Spatial packages
  #- rasterio
  - pysal
  - pyproj
  - rasterstats
  - geopy
  - cartopy
  #- geopandas
  - contextily
  - earthpy=0.9.2
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy
  - xarray
  - scipy


  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
